title: Michèle GABA
#logo: /assets/img/headshot_circle.png
description: Cliquer sur "Fork me on Github" à gauche pour accéder à l'ensemble des projets
#show_downloads: true
theme: jekyll-theme-merlot
